In [1]:
from sqlalchemy import create_engine,text
import pandas as pd 
import os
import pymysql
import numpy as np

In [20]:
import pandas as pd

from sqlalchemy import create_engine

engine1 = create_engine("mysql+pymysql://root:piit2026@localhost:3306/piit")

df = pd.read_sql("SELECT * FROM emp", engine)

print(df.head())
engine1

   empno   ename        job     mgr    hiredate     sal  comm  deptno
0   1234  MUNIRA    MANAGER  7839.0  1982-01-23  5000.0   NaN      10
1   7369   SMITH      CLERK  7902.0  1980-12-17   800.0   NaN      20
2   7788   SCOTT    ANALYST  7566.0  1982-12-09  3000.0   NaN      20
3   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0   NaN      10
4   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0   0.0      30

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [21]:
q("select min(sal) from emp")

   min(sal)
0     800.0

In [22]:
q("select * from dept")

    deptno       dname       loc
0     20.0    RESEARCH    DALLAS
1     30.0       SALES   CHICAGO
2     40.0  OPERATIONS    BOSTON
3     10.0  ACCOUNTING  NEW YORK
4     20.0    RESEARCH    DALLAS
5     30.0       SALES   CHICAGO
6     40.0  OPERATIONS    BOSTON
7     10.0  ACCOUNTING  NEW YORK
8     20.0    RESEARCH    DALLAS
9     30.0       SALES   CHICAGO
10    40.0  OPERATIONS    BOSTON

In [23]:
q('show tables')

  Tables_in_piit
0           dept
1            emp
2         munira
3        student
4      studentb2

In [ ]:
q('select * from emp wher