## Connect MySQL To Python

In [5]:
import pandas as pd
from sqlalchemy import create_engine
#Conn = mysql.connector.connect(host='localhost',user='root',password='piit2026',database='dup')
Conn = create_engine("mysql+pymysql://root:piit2026@localhost:3306/piit")
Conn

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [4]:
sheet_id = "1OzAar2RPWjJ9OgvS0h3Fpj7JjsJ2TOijB623-SyM1DU"
gid1 ='1124164429'
gid2 ='1481659858'
url1 = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid1}"
url2 = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid2}"
print(url1, '\n', url1)

https://docs.google.com/spreadsheets/d/1OzAar2RPWjJ9OgvS0h3Fpj7JjsJ2TOijB623-SyM1DU/export?format=csv&gid=1124164429
 https://docs.google.com/spreadsheets/d/1OzAar2RPWjJ9OgvS0h3Fpj7JjsJ2TOijB623-SyM1DU/export?format=csv&gid=1124164429

In [6]:
empQ= "select * from emp"
empdf=pd.read_sql(empQ,Conn)
empdf.head()

   empno   ename        job     mgr    hiredate     sal  comm  deptno
0   1234  MUNIRA    MANAGER  7839.0  1982-01-23  5000.0   NaN      10
1   7369   SMITH      CLERK  7902.0  1980-12-17   800.0   NaN      20
2   7788   SCOTT    ANALYST  7566.0  1982-12-09  3000.0   NaN      20
3   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0   NaN      10
4   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0   0.0      30

In [7]:
deptQ= "select * from dept"
deptdf=pd.read_sql(deptQ,Conn)
deptdf.head()

   deptno       dname       loc
0    20.0    RESEARCH    DALLAS
1    30.0       SALES   CHICAGO
2    40.0  OPERATIONS    BOSTON
3    10.0  ACCOUNTING  NEW YORK
4    20.0    RESEARCH    DALLAS

In [8]:
emp_dept=pd.merge(empdf,deptdf,on ='deptno')
emp_dept

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1234,MUNIRA,MANAGER,7839.0,1982-01-23,5000.0,NaN,10,ACCOUNTING,NEW YORK
1,1234,MUNIRA,MANAGER,7839.0,1982-01-23,5000.0,NaN,10,ACCOUNTING,NEW YORK
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
3,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
4,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
5,7788,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20,RESEARCH,DALLAS
6,7788,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20,RESEARCH,DALLAS
7,7788,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20,RESEARCH,DALLAS
8,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,ACCOUNTING,NEW YORK
9,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,ACCOUNTING,NEW YORK
10,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,SALES,CHICAGO
11,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,SALES,CHICAGO
12,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,SALES,CHICAGO
13,7876,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20,RESEARCH,DALLAS
14,7876,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20,RESEARCH,DALLAS
15,7876,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20,RESEARCH,DALLAS
16,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30,SALES,CHICAGO
17,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30,SALES,CHICAGO
18,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30,SALES,CHICAGO
19,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20,RESEARCH,DALLAS
20,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20,RESEARCH,DALLAS
21,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20,RESEARCH,DALLAS
22,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,ACCOUNTING,NEW YORK
23,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,ACCOUNTING,NEW YORK